### PR TITLE
v1.16, add maintainer

### PR DESCRIPTION
**Pull request by mfansler**
This bumps to latest version, cleans up the recipe a bit, and adds me as a maintainer. Mostly a refresh from `grayskull` with `--strict-conda-forge` option.

## Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #18 
Closes #17 
Closes #16 
Closes #15

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by arturdaraujo** [comment]
@sugatoray This will help update another package on conda forge

**Comment by arturdaraujo** [comment]
@sugatoray

**Comment by sugatoray** [comment]
Thank you for the PR. Glad to have you onboard @mfansler.

**Review by sugatoray — APPROVED** [review]

**Pull request merged**
